export const BasketRadioButtons = ({ onChange, checkBoxHandle }) => {
  return (
    <>
      <p>Choose a type:</p>
      <label>
        <input
          type="radio"
          name="messenger"
          value="email"
          onChange={checkBoxHandle}
        />
        email
      </label>
      <label>
        <input
          type="radio"
          name="messenger"
          value="viber"
          onChange={checkBoxHandle}
        />
        viber
      </label>
      <label>
        <input
          type="radio"
          name="messenger"
          value="telegram"
          onChange={checkBoxHandle}
        />
        telegram
      </label>
      <label>
        Contact
        <input
          type="text"
          name="contact"
          placeholder="example@mail.com"
          onChange={onChange}
        />
      </label>
    </>
  );
};
